/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4/userguide/building_java_projects.html
 */


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    //JUnit test framework.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2") 
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
    
    implementation("commons-io:commons-io:2.11.0")
    implementation("org.apache.commons:commons-lang3:3.12.0")
}

application {
    // Define the main class for the application.
    mainClass.set("io.github.ironking24.HackAssembler.HackAssembler")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}